import { AiCitationList } from "./AiCitationList.jsx";

const noticeLabels = Object.freeze({
  VERIFY_AUTHORITATIVE_DATA: "Verify important details in the authoritative OpsPilot view.",
  USE_STANDARD_SUPPORT: "Use standard OpsPilot support for account-specific help.",
  SNAPSHOT_MAY_BE_STALE: "The operational snapshot may have changed since it was prepared.",
});

const outcomeLabels = Object.freeze({
  ANSWER: "AI-generated answer",
  INSUFFICIENT_EVIDENCE: "Not enough document evidence",
  REFUSAL: "Request not answered",
  ESCALATE: "Standard support recommended",
});

export function AiResponsePanel({ response }) {
  if (!response) return null;

  return (
    <section className="panel ai-response" aria-live="polite" aria-labelledby="ai-response-title">
      <p className="eyebrow">{response.outcome}</p>
      <h2 id="ai-response-title">{outcomeLabels[response.outcome]}</h2>
      <p className="ai-answer-text">{response.answer}</p>
      <AiCitationList citations={response.citations} />
      {response.notices?.length > 0 ? (
        <ul className="ai-response-notices">
          {response.notices.map((notice) => (
            <li key={notice}>{noticeLabels[notice]}</li>
          ))}
        </ul>
      ) : null}
      <p className="muted">This text was generated by AI and is not stored as chat history.</p>
    </section>
  );
}
